const variables = {
    en: {
        developers: 'Developers',
        validators: 'Validators',
        stakedrop: 'Stakedrop',
        docs: 'Docs',
        blog: 'Blog',
        updates: 'Updates',

        smart_contracts_evolved: 'Smart Contracts Evolved.',
        section1_content: 'Use & create interoperable applications on Juno. A decentralized, public, permission-less network for cross-chain smart contracts.',
        get_started: 'Start Building',
        view_on_github: 'Ecosystem',

        contracts_deployed: 'Contracts Deployed On Juno',
        juno_network_validators: 'Juno Network Validators',
        juno_ecosystem_developers: 'Juno Ecosystem Developers',

        interoperable_smart_contracts: 'Interoperable Smart Contracts - Home of CosmWasm',
        interoperable_smart_contracts_section1: 'Juno is the permissionless neutral home of CosmWasm interoperable smart contracts and the InterWasm DAO. The ecosystem is pioneering CosmWasm development and adoption.',
        interoperable_smart_contracts_section2: 'Juno as a layer 1 smart contract network solves the first generation smart contract bottlenecks which are limited scalability, high cost for deployment and execution and offers an easy environment for developers across the globe to deploy scalable, secure decentralized applications efficiently.',
        interoperable_smart_contracts_section3: 'CosmWasm, enables WebAssembly (WASM) virtual machines (VMs). WebAssembly allows for software written in many languages to run securely on a blockchain. WASM serves as an intermediate language that compiles the developer’s language of choice into a portable virtual machine. This means that you can have a simple, secure and fast virtual machine set up to sandbox or partition your application’s actions for better testing, security, performance and speed.',

        section4_name_speed: 'Speed',
        section4_content_speed: 'Built on the Cosmos SDK ensures high throughput and fast contract execution',
        section4_name_cost: 'Cost',
        section4_content_cost: 'Low cost deployment up to 35000 times cheaper than gen 2 blockchain networks',
        section4_name_inter: 'Interoperability',
        section4_content_inter: 'Deployment on Juno and interoperable with all networks in the cosmos ecosystem via IBC',
        section4_name_smart: 'Smart Contracts',
        section4_content_smart: 'Code & deploy your contracts in multiple languages via the powerful CosmWasm Contract framework',
        section4_name_evm: 'EVM',
        section4_content_evm: 'Port over your smart contracts from Ethereum or create new ones in solidity without the scalability hassle',

        contracts_work: 'Contracts that just work',
        network_launch: 'Network Launch',
        network_launch_content: 'The Juno network is expected to launch in Q2 2021. Currently 150+ validators and 20+ developers are organically contributing to bootstrap the network and working on integrations to ensure a smooth launch and user experience.',
        ibm_contracts_work: 'IBC Contracts that just work',
        ibm_contracts_work_content: 'JUNO is set to launch with IBC capabilities. Making it the first smart contract zone in the cosmos ecosystem to provide interoperable smart contracts.',
        gravity_dex: 'Gravity DEX Listing',
        gravity_dex_content: 'Trading pairs for $JUNO i.e. JUNO/ATOM, JUNO/XPRT, JUNO/AKT, to name a few.',
        ibm_cosmos_hub: 'IBC (Cosmos Hub)',
        ibm_cosmos_hub_content: 'The goal is to make an early IBC connection to the Cosmos Hub.',
        smart_contract_browser: 'Smart Contract Browser',
        smart_contract_browser_content: 'The easiest way to interact with smart contracts is to have an easy to use contract browser directory & submition interface.',

        grass_roots_initiative: 'Grass Roots Initiative',
        grass_roots_initiative_content: ' Built by $ATOM holders and 100% distributed to staked atom holders. Juno is a decentralized effort to provide a sister hub to the Cosmos Hub. Primary purpose being to offload smart contract load to a designated zone while at the same time bringing utility back to the Hub. Atom holders have great incentive to ensure a fruitfull collaborative environment with the Cosmos Hub & eventually supplement security on Juno via Cosmos Hub shared security (Validator set).',
        grass_roots_card_head: 'BlockCreators / Juno',
        grass_roots_card_content: 'Smart contracts will make cosmos explode in usage. The community saw the need, and so they stepped up to the challenge. Juno is a true reflection of what people can accomplish when they work together.',

        want_juno_network: 'Want to contribute to the Juno network?',
        dev_discord: 'Dev Discord',

        meet_global_community: 'Meet the global social community.',
        telegram: 'Telegram',
        twitter: 'Twitter',
        discord: 'Discord',
        github: 'Github',

        roadmap: 'Roadmap',
        roadmap_year1: '2017',
        roadmap_heading1: 'JunoHack Phase 1 (Completed)',
        roadmap_text1: 'Incentivized smart contract challenge on Testnet',
        roadmap_year2: '2018',
        roadmap_heading2: 'Decentralized Main-net launch, October 1st 2021 (Completed)',
        roadmap_text2: '',
        roadmap_year3: '2019',
        roadmap_heading3: 'Keplr Self-integration (Completed)',
        roadmap_text3: '',
        roadmap_year4: '2020',
        roadmap_heading4: 'Osmosis AMM/DEX integration (Completed)',
        roadmap_text4: '',
        roadmap_year5: '2021',
        roadmap_heading5: 'Cosmostation wallet & Mintscan native integration (Completed)',
        roadmap_text5: '',
        roadmap_year6: '2022',
        roadmap_heading6: 'JunoScan Explorer (Completed)',
        roadmap_text6: '',
        roadmap_year7: '2023',
        roadmap_heading7: 'Sif Omni DEX integration (Completed)',
        roadmap_heading8: 'Gravity DEX / Emeris integration (Completed)',
        roadmap_heading9: 'Keplr native integration (In- Progress)',
        roadmap_heading10: 'UNI- Moneta testnet (In- Progress)',
        roadmap_heading11: 'Moneta Main-net upgrade',
        roadmap_heading12: 'Moneta Hacks go live (Incentivized dapp challenge)',
        roadmap_heading13: 'JunoSwap launch',
        roadmap_heading14: 'JunoMint launch',
        roadmap_heading15: 'Gravity DEX pool opening V.2',
    },
};

export default variables;
