const variables = {
    en: {
        developers: 'Developers',
        validators: 'Validators',
        stakedrop: 'Stakedrop',

        smart_contracts_evolved: 'Smart Contracts Evolved.',
        section1_content: 'Juno is an interoperable smart contract network. Highly scalable, robust, secure and easy to deploy!',
        get_started: 'Get Started',
        view_on_github: 'View On Github',

        contracts_deployed: 'Contracts Deployed On Juno',
        juno_network_validators: 'Juno Network Validators',
        juno_ecosystem_developers: 'Juno Ecosystem Developers',

        problems_juno_solves: 'Problems that JUNO solves',
        problems_juno_solves_section1: 'First generation smart contract networks have a common bottleneck which is limited scalability & high cost to deploy smart contracts.',
        problems_juno_solves_section2: 'Juno offers a blockchain network that scales to 10000 tps & and provides an environment for cost effective deployment at -99% reduced cost. All this while being the first mover to bring interoperable smart contracts to the blockchain world.',

        section4_name_speed: 'Speed',
        section4_content_speed: 'Built on the Cosmos SDK ensures high throughput and fast contract execution',
        section4_name_cost: 'Cost',
        section4_content_cost: 'Low cost deployment up to 35000 times cheaper than gen 2 blockchain networks',
        section4_name_inter: 'Interoperability',
        section4_content_inter: 'Deployment on Juno and interoperable with all networks in the cosmos ecosystem via IBC',
        section4_name_smart: 'Smart Contracts',
        section4_content_smart: 'Code your contracts in rust or Golang with the powerful CosmWasm Smart Contract Framework',
        section4_name_evm: 'EVM',
        section4_content_evm: 'Port over your smart contracts from Ethereum or create new ones in solidity without the scalability hassle',

        contracts_work: 'Contracts that just work',
        network_launch: 'Network Launch',
        network_launch_content: 'The Juno network is expected to October 1st, 2021. Currently 150+ validators and 20+ developers are organically contributing to bootstrap the network and working on integrations to ensure a smooth launch and user experience.',
        ibm_contracts_work: 'IBC Contracts that just work',
        ibm_contracts_work_content: 'JUNO is set to launch with IBC capabilities. Making it the first smart contract zone in the cosmos ecosystem to provide interoperable smart contracts.',
        gravity_dex: 'Gravity DEX Listing',
        gravity_dex_content: 'Trading pairs for $JUNO i.e. JUNO/ATOM, JUNO/XPRT, JUNO/AKT, to name a few.',
        ibm_cosmos_hub: 'IBC (Cosmos Hub)',
        ibm_cosmos_hub_content: 'The goal is to make an early IBC connection to the Cosmos Hub.',
        smart_contract_browser: 'Smart Contract Browser',
        smart_contract_browser_content: 'The easiest way to interact with smart contracts is to have an easy to use contract browser directory & submition interface.',
        hack_juno: "Hack Juno",
        hack_juno_content: 'HackJuno is a smart contract competition where developers can test their skills by coding next-generation, decentralized logic in Rust.',

        grass_roots_initiative: 'Grass Roots Initiative',
        grass_roots_initiative_content: ' Built by $ATOM holders and 100% distributed to staked atom holders. Juno is a decentralized effort to provide a sister hub to the Cosmos Hub. Primary purpose being to offload smart contract load to a designated zone while at the same time bringing utility back to the Hub. Atom holders have great incentive to ensure a fruitfull collaborative environment with the Cosmos Hub & eventually supplement security on Juno via Cosmos Hub shared security (Validator set).',
        grass_roots_card_head: 'BlockCreators / Juno',
        grass_roots_card_content: 'Smart contracts will make cosmos explode in usage. The community saw the need, and so they stepped up to the challenge. Juno is a true reflection of what people can accomplish when they work together.',

        want_juno_network: 'Want to contribute to the Juno network?',
        dev_discord: 'Dev Discord',

        meet_global_community: 'Meet the global social community.',
        telegram: 'Telegram',
        twitter: 'Twitter',
        discord: 'Discord',
        github: 'Github',

        roadmap: 'Roadmap',
        roadmap_year1: '2017',
        roadmap_heading1: 'JunoHack Phase 1 (Start date August 1st)',
        roadmap_text1: 'Incentivized smart contract challenge on Testnet',
        roadmap_year2: '2018',
        roadmap_heading2: 'Mainnet launch (Genesis after JunoHack. Hard date tba)',
        roadmap_text2: '',
        roadmap_year3: '2019',
        roadmap_heading3: 'Integration on Emeris',
        roadmap_text3: '',
        roadmap_year4: '2020',
        roadmap_heading4: 'Integration on Gravity DEX',
        roadmap_text4: '',
        roadmap_year5: '2021',
        roadmap_heading5: 'Integration on Osmosis AMM (Incentivized Pool)',
        roadmap_text5: '',
        roadmap_year6: '2022',
        roadmap_heading6: 'Moneta upgrade (Smart contract module. CosmWasm 1.0)',
        roadmap_text6: '',
        roadmap_year7: '2023',
        roadmap_heading7: 'JunoHack Phase 2 (Incentivized Smart contract challenge. Deployment on mainnet)',
    },
};

export default variables;
